### PR TITLE
Update init_hcismd_up.sh

### PR DESCRIPTION
**Pull request by blindpappu**
some of the if loop spelling was wrong. 
changed!

### CODE REVIEW

**Comment by Danct12** [comment]
[Nah.](https://www.youtube.com/watch?v=7kIno1naQcI)

**Comment by diamondburned** [comment]
That's not wrong, yours is wrong. There are only two proper ways to do the loop, and yours is neither.

```sh
if [ "$cond" -lt 1 ]; then
```

```sh
if [ "$cond" -lt 1 ]
then
```

Your way is redundant. Not to mention, I personally hate using 2 lines for such statements.

**Comment by asriel-danctnix** [comment]
If this wasn't a troll request, here's a **free** ticket to [Bash Academy](https://guide.bash.academy) if you need to learn (ba)sh.

**Comment by asriel-danctnix** [comment]
Is this **a fucking joke**? You just corrected all the `fi` to `if`, and congrats, you broke the script! \o/

**Comment by DolphinChips** [comment]
how to *not* create patches:
1. listen to spell checker in word
2. never test the thing
3. create a patch using github edit feature

**Pull request closed without merging**
